  version: '3'
  services: 
    backend:
      build:
        context: ./backend
      ports:
        - "5000:5000"
      networks:
        - mern-network
      

    frontend: 
      build: 
        context: ./frontend
      ports:
        - "8000:80"
    
    mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
      networks:
        - mern-network
      
  networks:
    mern-network:
      driver: bridge